### ISSUE TITLE
Not sure where esle to post this...so, can someone explain this in some more depth, I am not sure how to work around this

### ISSUE THREAD

**Issue by afm-mike** [koniu/recoll-webui#52]
Can't open files when Recoll WebUI is running on a server

By default links to files in the result list correspond to the file's physical location on the server. If you have access to the file tree via a local mountpoint or eg. ftp/http you can provide replacement URLs in the WebUI settings. If in doubt, ask your network administrator.

Recoll WebUI is running on server,  on debian.  No local mount points exist on the windows machines.

**Comment by medoc92** [comment]
Answered same question asked through email: use download link.

**Comment by koniu** [comment]
If you want to open instead of download you need to mount the file tree locally on the client machine and point the relevant 'Locations' in 'Settings' to that local mount point. 

To open files on windows machines you should probably look into setting up a Samba daemon on the server and "mount" the share on the Windows clients (`net use z: //server/my_docs` iirc). Then in the browser on the Windows client go to  Settings in recoll-webui and adjust folder Locations to correspond to the newly available Z:\... tree.
